### ISSUE TITLE
Why the Model weights File size increases as the training data Increases?

### ISSUE THREAD

**Issue by NavyaSreeYadavalli** [uber/ludwig#569] opened 2019-11-13 07:58 UTC
I have built a model with training data of 100 records with parallel-cnn as my encoder. Then the model-weights file size is 22MB. Now i changed my training file data to 1000 records and now my model-weights file size is 40MB.
Why there is a change in the size of weights file?

**Comment by msaisumanth** [comment] 2019-11-13 18:15
There's many reasons why this could happen. 

For example, have you checked how many epochs the model trained for in both cases? If one was trained for more epochs, there would be more metadata to save.

**Comment by w4nderlust** [comment] 2019-11-14 18:51
So the model weights file size should not change. Can you be specific about which files are actually growing in size?

**Comment by NavyaSreeYadavalli** [comment] 2019-11-19 13:36
model_hyperparameters 
model_weights.data-00000-of-00001 
train_set_metadata 
These 3 files are growing in size. But I want to know specifically why model_weights.data-00000-of-00001 file size changes based on training Data Size.

Number of epochs are same in both the cases. I am using parallel-cnn which is default one. No additional changes in my model-definition file

**Comment by w4nderlust** [comment] 2019-11-20 01:14
model_hyperparameters and train_set_metadata may definitely change depending on the size of your data, as some of their contents are data dependent, like the vocabulary of classes or the vocabulary of words if you working on text.
The weights should not change though, we would want to know what that's the case too, but it is difficult without a reproducible example. If you can provide such a thing to use we would be glad to take a look at it.
What you need to provide is either a script or a command with the model definition you are using and some data, together with instructions on how to reproduce the issue. if you can't share your data, you can use the dataset synthesizer in `data/dataset_synthesyzer.py` to create a dataset.

**Comment by NavyaSreeYadavalli** [comment] 2019-11-25 13:22
2 sample data sets of news is considered of which one is of 100 records and another one of 1000 records. Tested with the testing_ludwig.py file which is in the attached zip file. Then the generated model_weights file size of 100 records is 19MB and of 1000 records is 22MB.

When i convert the same data using data_synthesizer.py by considering the features as 
'[\
  {name: Data, type: text, vocab_size: 256, max_len: 256}, \
  {name: Target_Class, type: category, vocab_size: 5} \
]'
and build the model , then the generated model_weights file size is constant that is 20MB for both the files.

Please do see the data and code and let me know why the weights file size is varying for my data.

Regarding Zip file:
1) new_trained_models-->folder consists of generated models.
2) testing_ludwig.py-->script file for training model.
3) news_train_100.csv , news_valid_100.csv are the training and validation files of 100 records.
4) news_train_1000.csv , news_valid_1000.csv are the training and validation files of 1000 records.

[Testing_Github.zip](https://github.com/uber/ludwig/files/3886463/Testing_Github.zip)

**Comment by NavyaSreeYadavalli** [comment] 2019-11-27 07:23
Any update on the above issue. Please do update why it is happening like that to me.

**Comment by w4nderlust** [comment] 2019-11-27 08:29
@NavyaSreeYadavalli we will look into it.

**Comment by surendra1472** [comment] 2019-12-06 03:09
Hi, How do I use this model weights file, how can I use this to find column importance.

**Comment by w4nderlust** [comment] 2020-02-15 04:13
@surendra1472 your question is not related to this issue, please open another issue for that. Also feature importance in DL models is an open research question ( https://stats.stackexchange.com/questions/261008/deep-learning-how-do-i-know-which-variables-are-important ), there are approaches like lime and shap that approximate it.

**Comment by w4nderlust** [comment] 2020-02-23 01:08
I finally had time to look into it. The 1000 sample dataset has a bigger vocabulary, because of that the first embedding layer in the model has a different dimension, 1294 in the case of the bigger dataset, 252 as you can see from the screenshots.

![Screenshot from 2020-02-22 17-06-09](https://user-images.githubusercontent.com/349256/75101716-ecd39a00-5595-11ea-8c32-77cbd7e6e263.png)

![Screenshot from 2020-02-22 17-06-48](https://user-images.githubusercontent.com/349256/75101717-ee04c700-5595-11ea-8e5c-199e7e009f8e.png)

Closing this as the mystery is solved :)

**Closed by w4nderlust** 2020-02-23 01:08 UTC
Labels: looking into it
