### ISSUE TITLE
Running Ludwig in Jupyter Notebook - Syntax error?

### ISSUE THREAD

**Issue by mgc26** [uber/ludwig#265] opened 2019-04-02 03:36 UTC
I think I may have stumbled upon a bug when attempting to use Ludwig in the jupyter notebook:

`# Running the Ludwig model with the CNN encoder
ludwig experiment --data_csv labels.csv --model_definition_file model_definitionCNN.yaml`

`File "<ipython-input-13-a836ac87ac8b>", line 2
    ludwig experiment --data_csv labels.csv --model_definition_file model_definitionCNN.yaml
                    ^
SyntaxError: invalid syntax`

The carrot is pointing to the end of ludwig experiment.

Anyone else see this?

**Comment by w4nderlust** [comment] 2019-04-02 05:52
That is a shell command, not python code.
For using Ludwig in a jupyter notebook you need to use the programmatic api.
Alternatively, you can run shell commands with `!` before the command, but why would you want to do that when you can call the command from the command line I'm not sure.
Not a bug anyway, so I'm closing this.

**Closed by w4nderlust** 2019-04-02 05:52 UTC
