### ISSUE TITLE
[bug] ErrorScore should operate with tensors

### ISSUE THREAD

**Issue by ifokeev** [uber/ludwig#820] opened 2020-08-13 18:01 UTC
<img width="1200" alt="Screenshot 2020-08-13 at 20 59 52" src="https://user-images.githubusercontent.com/2017148/90169993-0d8fe600-dda8-11ea-9479-0d4c0618a402.png">

The issue is some here:
https://github.com/uber/ludwig/blob/master/ludwig/modules/metric_modules.py#L97

Getting this with `experimental_run_functions_eagerly(False)`

**Comment by w4nderlust** [comment] 2020-08-14 23:31
Yes we are already working on this. @jimthompson5802 FYI this happens if `experimental_run_functions_eagerly(False)`.

**Comment by jimthompson5802** [comment] 2020-08-14 23:37
Acknowledging that I'm working on this.

**Comment by w4nderlust** [comment] 2020-08-15 04:37
@ifokeev would you mind testing out the current master after the merge of the PR that should solve this issue?

**Comment by w4nderlust** [comment] 2020-08-16 22:43
Closing for the time being. Let us know if the problem is still there and we can reopen it.

**Closed by w4nderlust** 2020-08-16 22:43 UTC
Labels: bug, waiting for answer
