### ISSUE TITLE
problems about yaml file

### ISSUE THREAD

**Issue by Kantshun** [uber/ludwig#503] opened 2019-08-24 14:45 UTC
I just know python language, I have no idea about how to edit .yaml files.
Is there any material about yaml for beginner?
Furthermore, I'm working on some gene data analysis project, there are thousands of input features and output features. According to user guide, I have to type these features word by word by hand which is really a torture to me. Is there any way I can configure yaml files more effectively?

Is there anyone can help me? Thank you.

**Comment by flozi00** [comment] 2019-08-24 15:12
You could write a python script what takes to first line of csv file and builds the yaml file from this.
Automating ludwig for such task would be really great.
Just have a look to the examples page of ludwig in docs for understanding yaml file building.

**Comment by w4nderlust** [comment] 2019-08-25 02:54
You dan create your model configuration programmatically in python by creating a disctionary and save it with `yaml.dump(my_dict, file)`.
Other users have requested a similar feature, the problem is that it doesn't seem like there's a unified convention about naming feature columns, so it's probably much more efficient writing 4 lines of ad hoc python every time than a single process that encompasses all possibilities.
So setting this to wontfix and closing it, but if someone has some good ideas about ways to implement this, feel free to write it here and we can discuss.

**Closed by w4nderlust** 2019-08-25 02:54 UTC
