### ISSUE TITLE
Difference between 'ludwig predict' and 'ludwig serve'

### ISSUE THREAD

**Issue by myzarak** [uber/ludwig#661] opened 2020-03-23 11:45 UTC
# Description of the bug
Hello,

I find an issue with the contribution serve.py.

I tried to use 'ludwig serve' with a python client to send data to a trained model but I notice a difference if I send a csv file to 'ludwig predict' again sending file to 'ludwig serve' through python client.

After investigation, I deduce that the problem is due to a wrong managing of null input field.

Basically, 'Ludwig Serve' requiered all input features (function convert_input from serve.py) , so you need to define all input features inside the client.
But convert_input() not allow to retrieve None data (None / "" / '').

Is it possible to manage empty data into convert_input ? Or to add a new feature in serve.py in order to enable to request the REST API directly with a json ? ( Maybe we could protect the input data with a serializer construct with pydentic build by using input_features )

# To Reproduce
1. Load your model: 
ludwig serve --model_path ../../ --port 5000

2. Request the server with a client:

Python client which send text data to ludwig serve
import requests
file={
        'some input parameters': (None, 'some text data'),
        'some none imput parameters': (None, ''),
        'some none imput parameters': (None, None), # Raise an error on client side
        'some none imput parameters': None, # Raise an error on client side
    }
r = requests.post(url, files=file)
print(r.json())

# Environment
- OS: Windows 10 Pro
- Python version: 3.6.8
- Ludwig version: 0.2.1 & 0.2.2.3

#Additional context
In addition, find below my json request.body json parser:

Initial function
@app.post('/predict')
async def predict(request: Request):
    form = await request.form()
    files, entry = convert_input(form)
    

I test to add a new function to serve.py which retrieve json directly from body request (Json allow safely to initialize None field)
This different approach produce the same results as 'ludwig predict'

import json
@app.post('/predict_json')
async def predict_json(request: Request):
    entry = await request.body()
    entry = json.loads(entry.decode())

**Comment by w4nderlust** [comment] 2020-03-23 23:30
@myzarak thanksfor posting this, let me try to undesrand better the problem.
First of all, why do you want to send None?
Second, what is the difference in terms of outputs from the server and by running predict? Can you provide a specific example that I can reproduce?

In general, all lists associated with all input fields must contain the same number of values, so your example
```
 'some none imput parameters': None, # Raise an error on client side
```
is wrong, but in the other cases, where the length is correct, I understand that there is a problem with those too if they contain None, is this correct?
Again a completely reproducible example will enable me to look into this. Please provide code / data/ command / yaml / pretrained model for me to test. If the data or the model cannot be shares, you can use the script in `data/dataset_synthesizer.py to generate synthetic data.

**Comment by myzarak** [comment] 2020-03-25 11:22
@w4nderlust 

Thank you for the answer.

Your right, due to my company policy I couldn't share data. I will try to send you fastly synthetic data and model to reproduce.

To respond to your questions:

When you train a model which have to process text, the text data is provide to ludwig inside a csv file. If one cell of the csv file is empty, the dataframe generate by ludwig return NaN value (equivalent to None) for the empty cells. That's not a problem, it's just the behavior. 

But, with the REST Api, i don't want to lose time to put my input data vector inside a binary csv which one should be save temporarly by ludwig and process after to construct a dataframe. So, I try to send directly my input data. In that specific case, on the client side, it's seems to be not possible to send empty data (like None), I could only send blank (like ""). But, if I display the dataframe build by ludwig, I notice that the only difference between the two methods is  the  NaN/Blank cells.

So, my first approach should be to try to find a solution which allow the client to send 1 None field (Field is define with None value) without success ( I spare a very lot's of time on this question without finding a solution ).
My second approach should be to write another ludwig REST Api input (called predic_json) which received not a files, but a json ( which allow to send None data. ) and this function returned to me exactly the same result like a standard predict with the csv file.

In terms of results:
ludwig predict with csv:  
{'tag_predictions': 'CLASS_1', 'tag_probability': 0.532364}

ludwig serve with manual input data:  
{'tag_predictions': 'undefined', 'tag_probability': 0.5043553113937378}

ludwig serve with custom json function:  
{'tag_predictions': 'CLASS_1', 'tag_probability': 0.532364}

**Comment by w4nderlust** [comment] 2020-03-26 01:31
Thanks for the additional details, we'll look into it!
@johnwahba maybe you can help on this?

**Comment by johnwahba** [comment] 2020-03-26 01:45
@myzarak if you can provide a synthetic model, a curl that repros, and what you want it to provide, that'll be ideal. :)

**Comment by w4nderlust** [comment] 2020-09-19 00:33
@myzarak do you have any update for us? can you provide a reproducible example? Even a manually defined 2 lines csv would suffice, but without being able to reproduce the issue we won't be able to solve it.

**Comment by w4nderlust** [comment] 2020-09-19 00:56
I also improved the test of the server to make sure that the outputs from it are the same you obtain from a local model: https://github.com/uber/ludwig/commit/e576bcaf331ce34d8569197ad9fc7c0eab4a7d0f

I would be happy to include tests for corner cases with None inside but I need an example of that.

**Comment by w4nderlust** [comment] 2020-09-29 00:02
Closing due to staleness. I believe the recent changes for v0.3 solved the issue, but if not please post again here and i will be happy to fix any issue.

**Closed by w4nderlust** 2020-09-29 00:02 UTC
Labels: looking into it, waiting for answer
