### ISSUE TITLE
 How to plot correctly Confusion Matrix/Heatmap

### ISSUE THREAD

**Issue by renatochacon** [uber/ludwig#368] opened 2019-06-07 03:56 UTC
Hello. I've trained and tested the Titanic dataset using an yaml file just like that one you provided here: https://uber.github.io/ludwig/examples/

I'm trying to make a heatmap like this one: 

![image](https://user-images.githubusercontent.com/45271643/59080393-dded7000-88be-11e9-9465-c145845cbaac.png)

but I can't seem to find the right parameters and/or how to use them. It states on your website that:
"This visualization uses the top_n_classes, normalize, ground_truth_metadata, test_statistics and model_names parameters. For each model (in the aligned lists of test_statistics and model_names) it produces a heatmap of the confusion matrix in the predictions for each field that has a confusion matrix in test_statistics. The value of top_n_classes limits the heatmap to the n most frequent classes."

I used this command on terminal: $ ludwig visualize --visualization confusion_matrix --normalize --top_n_classes 8 --ground_truth_metadata train.json --test_statistics results_0/test_statistics.json --model_names models

my questions are:
1 - I succeeded on generate a matrix_confusion file but I'm just not getting how to obtain a heatmap. How can I get it?
2 - I've read the whole web page but I still don't know what to write when using --model_names and --top_n_classes parameters. In the terminal command provided above, I just put random values like "8" and "models" for those parameters. Considering that I'm using the exact yaml file from your webpage, could you give me an example on how to apply it correctly?

**Comment by w4nderlust** [comment] 2019-06-08 22:28
@renatochacon can you please specify what's wrong with the command you are using? Do you get errors? I think the issue is probably that the titanic dataset output is a binary one, while we actually compute the confusion matrix for the multiclass case. In that case we may actually add it for the binary case too.

**Comment by w4nderlust** [comment] 2019-07-21 00:05
In the case of binary features you don't have to specify anything other than the test statistics file, the other parameters are useful for classification problems.

Anyway tested this with binary features, and I can confirm it works.

![Figure_1](https://user-images.githubusercontent.com/349256/61585462-6858fe80-ab10-11e9-9fa6-fd5326384d96.png)

Closing for now, please let me know if you still have issues and I will reaopen.

**Closed by w4nderlust** 2019-07-21 00:05 UTC
Labels: waiting for answer
