### ISSUE TITLE
No output at Kaggle

### ISSUE THREAD

**Issue by leokury** [uber/ludwig#413] opened 2019-07-04 19:55 UTC
**Describe the bug**
After installing the package in Kaggle, I run the script successfully but no output appears.

When executing the same script on my machine the output is normally displayed.

Is there any configuration I need to do to display the output in kaggle? I already tried debug and logging_level parameters but it not worked.

**To Reproduce**
Use this script here: https://www.kaggle.com/leokury/ludwig-testing/code

No ludwig output is shown.

**Expected behavior**
Produce same output as local machine.

**Comment by TKassis** [comment] 2019-07-04 22:09
Maybe I'm misunderstanding this, but the output seems to be there under the output tab on the left. What kind of output are you expecting? 

![Annotation 2019-07-04 180908](https://user-images.githubusercontent.com/9168908/60688978-d8b41e80-9e86-11e9-8aff-02467ac759fa.png)

**Comment by leokury** [comment] 2019-07-05 11:53
Sorry, I'm talking about text output on the progress of the model. Ludwig is not printing any text to standard output.

![AwesomeScreenshot-ludwig-testing-Kaggle-2019-07-05-08-07-29](https://user-images.githubusercontent.com/620050/60720779-33d72700-9f02-11e9-9870-49b6834aa5b4.png)

**Comment by dsblank** [comment] 2019-07-05 12:03
There were some recent fixes with logging applied to ludwig master that haven't been released yet. You might want to try running from master, or wait until the next release.

**Comment by leokury** [comment] 2019-07-05 16:29
I already installed it from master:

`pip install git+https://github.com/uber/ludwig`

But still with same problem.

**Comment by msaisumanth** [comment] 2019-07-05 21:45
@leokury why are you importing logging in your script? Could you remove that line and try? 

In the meantime, I'll try to reproduce this error and check what's the issue.

**Comment by msaisumanth** [comment] 2019-07-05 22:05
@leokury looking into it. In the meantime, use the CLI tool if possible.

**Comment by msaisumanth** [comment] 2019-07-05 23:27
@leokury your issue will be fixed once this [pr](https://github.com/uber/ludwig/pull/412) is merged. 

Also, Ludwig's API by default only prints errors. So if you want more information, you'll have to modify your code to set the logging level, like this: 

model = LudwigModel(model_definition, logging_level=logging.DEBUG)
train_stats = model.train(train_df.head(10), logging_level=logging.DEBUG)

**Comment by w4nderlust** [comment] 2019-07-06 00:19
Merged the PR, @eokury can you please confirm it works now?

**Comment by leokury** [comment] 2019-07-06 12:16
I confirm that using the latest version of the master and including the logging DEBUG text output is printed.

Thanks guys!

Just one question, by default should ludwig not print the model's progress? When I used it on my local machine ludwig was printing the progress, even without using DEBUG logging. It would be interesting to standardize or document it.

**Comment by msaisumanth** [comment] 2019-07-06 13:49
@leokury Thanks for confirming. We'll update the documentation. The logging levels are set differently for the CLI and the API.

**Closed by msaisumanth** 2019-07-06 13:49 UTC
Labels: bug, waiting for answer
