### ISSUE TITLE
AttributeError: 'list' object has no attribute 'encode'

### ISSUE THREAD

**Issue by rthiruv-lab58** [uber/ludwig#478] opened 2019-08-05 15:00 UTC
**Describe the bug**
When I was trying to visualize on compare_classifiers_predictions_distribution, I got this error, saying 
AttributeError: 'list' object has no attribute 'encode'

Run this command:
ludwig visualize --visualization compare_classifiers_predictions_distribution --ground_truth path/to/train.hdf5 --test_statistics results_1/test_statistics.json --predictions path/to/results_0

Please provide code, yaml definition file and a sample of data in order to entirely reproduce the issue.
The YAML file for the model

input_features:
    -
        name: data
        type: image
        encoder: resnet

preprocessing:
    image:
        in_memory: true
        resize_method: interpolate
        height: 640
        width: 480
        num_channels: 1
       
output_features:
    -
        name: emotions
        type: category
        
training:
    batch_size: 16
    epochs: 50 
    early_stop: 5
    learning_rate: 0.001

**Expected behavior**
the compare_classifiers_predictions_distribution plot to be visualized.

**Screenshots**
![error](https://user-images.githubusercontent.com/51823700/62473898-b8220180-b76f-11e9-9a62-f4cc310cf211.png)

**Environment (please complete the following information):**
 - OS: iOS
 - Version 10.14.5
- Python version 3.7.3
- Ludwig version 0.2

**Additional context**
I had all the necessary files as described in the visualization page here https://uber.github.io/ludwig/user_guide/#compare_classifiers_predictions_distribution
but somehow this error persists.

**Comment by msaisumanth** [comment] 2019-08-05 17:43
@rthiruv-lab58 I think you're missing one more argument: field. Could you please check if that's the issue?

**Comment by rthiruv-lab58** [comment] 2019-08-05 18:14
> @rthiruv-lab58 I think you're missing one more argument: field. Could you please check if that's the issue?

I did not use the field parameter, because for "compare_classifiers_multiclass_multimetric"  visualization, It worked without the field parameters.
I thought it (field) had a default value, which it clearly does not have. What threw me off, was the encoding format, which I was not able to track back to the h5py script.

**Comment by msaisumanth** [comment] 2019-08-05 21:52
right. yeah, the error message wasn't really helpful. Did that resolve the issue?

**Comment by rthiruv-lab58** [comment] 2019-08-13 13:44
> right. yeah, the error message wasn't really helpful. Did that resolve the issue?

Hello, sorry for the late reply. I was looking through the documentation, but i could not understand how to generate the field value (for the ground truth) or if it is generated during the process of training, where it is stored. Any insights on that will be useful.

**Comment by w4nderlust** [comment] 2019-08-13 21:07
The field is just the name of the column you are predicting.

**Comment by rthiruv-lab58** [comment] 2019-08-14 14:57
@w4nderlust thank you for the response. I understand what the field is now.
When i was trying to visualize with the field argument, the following was printed: 
[2 6 1 4 5 3 7 8 0] 
A list with 9 elements. I saw the sample image in the documentation having 10(0-9) elements  So when i ran the visualization for compare_classifiers_predictions_distribution, 
The list index out of error arises which makes sense because the prediction is on 8 classes and not 9. I wonder if the 'UNK' class prediction causes the index to be thrown off. 

for the prediction argument i pointed the numpy array for predictions stored in results_0

the snippet for #Draw polygon representing values 

for i, alg_predictions in enumerate(predictions):
        draw_polygon(alg_predictions, algorithms[i], colors[i])

 Screenshot of the new error.
![polygon_error](https://user-images.githubusercontent.com/51823700/63030884-1b531880-be81-11e9-8744-bf230513facf.png)

**Comment by w4nderlust** [comment] 2019-08-14 19:13
Can you please provide a minimal reproducible example?
The predictions from the model have one more class that the ones in the ground truth because of the UNK, but that shouldn't be a problem.
As a reference i would suggest you to look at the test `test_visualisation_cmp_classifiers_predictions_distribution_output_saved` in `tests/integration_tests/test-visualization.py`

**Comment by w4nderlust** [comment] 2020-09-29 00:19
Closing due to staleness, feel free to reopen if needed.

**Closed by w4nderlust** 2020-09-29 00:19 UTC
Labels: waiting for answer
