### ISSUE TITLE
Invalid Argument Error

### ISSUE THREAD

**Issue by art-hack** [uber/ludwig#199] opened 2019-03-11 18:35 UTC
I am getting Invalid argument error when i try to train the dataset

```
(venv) (base) quadro@Quadro:~/Desktop/Work/contest/ludwig$ ludwig train --data_csv train/train_file.csv -mdf train/model.yaml 
 _         _        _      
| |_  _ __| |_ __ _(_)__ _ 
| | || / _` \ V  V / / _` |
|_|\_,_\__,_|\_/\_/|_\__, |
                     |___/ 
ludwig v0.1.0 - Train

Experiment name: experiment
Model name: run
Output path: results/experiment_run_3


ludwig_version: '0.1.0'
command: ('/home/quadro/Desktop/Work/contest/ludwig/venv/bin/ludwig train --data_csv '
 'train/train_file.csv -mdf train/model.yaml')
commit_hash: '7dc539a0590c'
dataset_type: 'generic'
random_seed: 42
input_data: 'train/train_file.csv'
model_definition: {   'combiner': {'type': 'concat'},
    'input_features': [   {   'name': 'ID',
                              'tied_weights': None,
                              'type': 'numerical'},
                          {   'name': 'UsageClass',
                              'tied_weights': None,
                              'type': 'category'},
                          {   'name': 'CheckoutType',
                              'tied_weights': None,
                              'type': 'category'},
                          {   'name': 'CheckoutYear',
                              'tied_weights': None,
                              'type': 'numerical'},
                          {   'name': 'CheckoutMonth',
                              'tied_weights': None,
                              'type': 'numerical'},
                          {   'name': 'Checkouts',
                              'tied_weights': None,
                              'type': 'numerical'},
                          {   'encoder': 'parallel_cnn',
                              'level': 'word',
                              'name': 'Title',
                              'tied_weights': None,
                              'type': 'text'},
                          {   'encoder': 'parallel_cnn',
                              'level': 'word',
                              'name': 'Creator',
                              'tied_weights': None,
                              'type': 'text'},
                          {   'name': 'Subjects',
                              'tied_weights': None,
                              'type': 'category'},
                          {   'encoder': 'parallel_cnn',
                              'level': 'word',
                              'name': 'Publisher',
                              'tied_weights': None,
                              'type': 'text'},
                          {   'encoder': 'parallel_cnn',
                              'level': 'word',
                              'name': 'PublicationYear',
                              'tied_weights': None,
                              'type': 'text'},
                          {   'name': 'MaterialType',
                              'tied_weights': None,
                              'type': 'category'}],
    'output_features': [   {   'dependencies': [],
                               'loss': {   'type': 'mean_squared_error',
                                           'weight': 1},
                               'name': 'ID',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'type': 'numerical',
                               'weight': 1},
                           {   'dependencies': [],
                               'loss': {   'class_distance_temperature': 0,
                                           'class_weights': 1,
                                           'confidence_penalty': 0,
                                           'distortion': 1,
                                           'labels_smoothing': 0,
                                           'negative_samples': 0,
                                           'robust_lambda': 0,
                                           'sampler': None,
                                           'type': 'softmax_cross_entropy',
                                           'unique': False,
                                           'weight': 1},
                               'name': 'MaterialType',
                               'reduce_dependencies': 'sum',
                               'reduce_input': 'sum',
                               'top_k': 3,
                               'type': 'category'}],
    'preprocessing': {   'bag': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000},
                         'binary': {   'fill_value': 0,
                                       'missing_value_strategy': 'fill_with_const'},
                         'category': {   'fill_value': '<UNK>',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 10000},
                         'force_split': False,
                         'image': {   'in_memory': True,
                                      'missing_value_strategy': 'backfill',
                                      'resize_method': 'crop_or_pad'},
                         'numerical': {   'fill_value': 0,
                                          'missing_value_strategy': 'fill_with_const'},
                         'sequence': {   'fill_value': '',
                                         'format': 'space',
                                         'lowercase': False,
                                         'missing_value_strategy': 'fill_with_const',
                                         'most_common': 20000,
                                         'padding': 'right',
                                         'padding_symbol': '<PAD>',
                                         'sequence_length_limit': 256,
                                         'unknown_symbol': '<UNK>'},
                         'set': {   'fill_value': '',
                                    'format': 'space',
                                    'lowercase': False,
                                    'missing_value_strategy': 'fill_with_const',
                                    'most_common': 10000},
                         'split_probabilities': (0.7, 0.1, 0.2),
                         'stratify': None,
                         'text': {   'char_format': 'characters',
                                     'char_most_common': 70,
                                     'char_sequence_length_limit': 1024,
                                     'fill_value': '',
                                     'lowercase': True,
                                     'missing_value_strategy': 'fill_with_const',
                                     'padding': 'right',
                                     'padding_symbol': '<PAD>',
                                     'unknown_symbol': '<UNK>',
                                     'word_format': 'space_punct',
                                     'word_most_common': 20000,
                                     'word_sequence_length_limit': 256},
                         'timeseries': {   'fill_value': '',
                                           'format': 'space',
                                           'missing_value_strategy': 'fill_with_const',
                                           'padding': 'right',
                                           'padding_value': 0,
                                           'timeseries_length_limit': 256}},
    'training': {   'batch_size': 128,
                    'bucketing_field': None,
                    'decay': False,
                    'decay_rate': 0.96,
                    'decay_steps': 10000,
                    'dropout_rate': 0.0,
                    'early_stop': 5,
                    'epochs': 100,
                    'eval_batch_size': 0,
                    'gradient_clipping': None,
                    'increase_batch_size_on_plateau': 0,
                    'increase_batch_size_on_plateau_max': 512,
                    'increase_batch_size_on_plateau_patience': 5,
                    'increase_batch_size_on_plateau_rate': 2,
                    'learning_rate': 0.001,
                    'learning_rate_warmup_epochs': 5,
                    'optimizer': {   'beta1': 0.9,
                                     'beta2': 0.999,
                                     'epsilon': 1e-08,
                                     'type': 'adam'},
                    'reduce_learning_rate_on_plateau': 0,
                    'reduce_learning_rate_on_plateau_patience': 5,
                    'reduce_learning_rate_on_plateau_rate': 0.5,
                    'regularization_lambda': 0,
                    'regularizer': 'l2',
                    'staircase': False,
                    'validation_field': 'combined',
                    'validation_measure': 'loss'}}


Using full raw csv, no hdf5 and json file with the same name have been found
Building dataset (it may take a while)
Loading NLP pipeline
/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/features/numerical_feature.py:63: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
Writing dataset
Writing train set metadata with vocabulary
Training set: 22220
Validation set: 3125
Test set: 6308
  embedding_size (50) is greater than vocab_size (2). Setting embedding size to be equal to vocab_size.
  embedding_size (50) is greater than vocab_size (2). Setting embedding size to be equal to vocab_size.
  embedding_size (50) is greater than vocab_size (9). Setting embedding size to be equal to vocab_size.

╒══════════╕
│ TRAINING │
╘══════════╛

2019-03-12 00:00:50.143030: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

Epoch   1
Training:   0%|                                                                                                                                                                             | 0/174 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'ID/ID_placeholder' with dtype float and shape [?]
	 [[{{node ID/ID_placeholder}} = Placeholder[dtype=DT_FLOAT, shape=[?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/bin/ludwig", line 11, in <module>
    load_entry_point('ludwig==0.1.0', 'console_scripts', 'ludwig')()
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/cli.py", line 86, in main
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/cli.py", line 64, in __init__
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/cli.py", line 70, in train
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/train.py", line 729, in cli
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/train.py", line 272, in full_train
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/train.py", line 426, in train
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/models/model.py", line 520, in train
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'ID/ID_placeholder' with dtype float and shape [?]
	 [[node ID/ID_placeholder (defined at /home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/features/numerical_feature.py:79)  = Placeholder[dtype=DT_FLOAT, shape=[?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'ID/ID_placeholder', defined at:
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/bin/ludwig", line 11, in <module>
    load_entry_point('ludwig==0.1.0', 'console_scripts', 'ludwig')()
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/cli.py", line 86, in main
    CLI()
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/cli.py", line 70, in train
    train.cli(sys.argv[2:])
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/train.py", line 729, in cli
    full_train(**vars(args))
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/train.py", line 272, in full_train
    debug=debug
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/train.py", line 409, in train
    debug=debug
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/models/model.py", line 110, in __init__
    **kwargs
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/models/model.py", line 160, in __build
    is_training=self.is_training
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/models/inputs.py", line 39, in build_inputs
    **kwargs)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/models/inputs.py", line 66, in build_single_input
    **kwargs)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/features/numerical_feature.py", line 89, in build_input
    placeholder = self._get_input_placeholder()
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/features/numerical_feature.py", line 79, in _get_input_placeholder
    name='{}_placeholder'.format(self.name)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1747, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5206, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'ID/ID_placeholder' with dtype float and shape [?]
	 [[node ID/ID_placeholder (defined at /home/quadro/Desktop/Work/contest/ludwig/venv/lib/python3.6/site-packages/ludwig-0.1.0-py3.6.egg/ludwig/features/numerical_feature.py:79)  = Placeholder[dtype=DT_FLOAT, shape=[?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


```

Incase you want to know my model.yaml config, it is like this:

```
input_features:
    -
        name: ID
        type: numerical
    -
        name: UsageClass
        type: category
    -
        name: CheckoutType
        type: category
    -
        name: CheckoutYear
        type: numerical
    -
        name: CheckoutMonth
        type: numerical
    -
        name: Checkouts
        type: numerical
    -
        name: Title
        type: text
    -
        name: Creator
        type: text
    -
        name: Subjects
        type: category
    -
        name: Publisher
        type: text
    -
        name: PublicationYear
        type: text
    -
        name: MaterialType
        type: category

output_features:
    -
        name: ID
        type: numerical
    -
        name: MaterialType
        type: category

```

**Comment by w4nderlust** [comment] 2019-03-11 19:22
Can you paste a small sample of your dataset? just the firt 4 lines would be enough.

**Comment by w4nderlust** [comment] 2019-03-11 19:25
Also, the problem is likely the fact that you are using the same name for both an input and an output feature (ID) which is currently not allowed.
Moreover, it's not clear to me why you would want to predict IDs and also use IDs as inputs, as they probably are unique for each order so they don't provide any information, and also they are technically categories not numbers, so encoding and decoding them as numbers is likely wrong.

**Comment by art-hack** [comment] 2019-03-11 19:30
```
ID,UsageClass,CheckoutType,CheckoutYear,CheckoutMonth,Checkouts,Title,Creator,Subjects,Publisher,PublicationYear,MaterialType
1,Physical,Horizon,2005,4,1,Tidal wave,,"Tsunamis, Tsunamis Juvenile literature",,,BOOK
2,Physical,Horizon,2005,4,1,London holiday / Richard Peck.,"Peck, Richard, 1934-",,"Viking,",1998.,BOOK
3,Physical,Horizon,2005,4,3,Cinco de Mayo : celebrating Hispanic pride / Carol Gnojewski.,"Gnojewski, Carol","Cinco de Mayo Mexican holiday History Juvenile literature, Mexican Americans Social life and customs Juvenile literature, Puebla Battle of Puebla de Zaragoza Mexico 1862 Juvenile literature, Cinco de Mayo Mexican holiday Juvenile literature, Holidays Juvenile literature, Mexico Social life and customs Juvenile literature","Enslow Publishers,",c2002.,BOOK
4,Physical,Horizon,2005,4,1,Annapolis,,"War stories, Historical fiction, Domestic fiction, Sea stories, United States Naval Academy History Fiction, United States Navy History Fiction, Family Maryland Annapolis History Fiction, United States History Naval Fiction, Annapolis Md History Fiction",,,BOOK
```

**Comment by art-hack** [comment] 2019-03-11 19:32
> Also, the problem is likely the fact that you are using the same name for both an input and an output feature (ID) which is currently not allowed.
> Moreover, it's not clear to me why you would want to predict IDs and also use IDs as inputs, as they probably are unique for each order so they don't provide any information, and also they are technically categories not numbers, so encoding and decoding them as numbers is likely wrong.

I just want to pass forward the original IDs in the output as well, but was unable to find any solutions for that

**Comment by w4nderlust** [comment] 2019-03-11 19:39
It's not really clear to me why you may want to do that. Anyway, try to remove both the ID input feature and ID output feature and it should work

**Comment by art-hack** [comment] 2019-03-11 19:48
Removing ID from both input and output and removing MaterialType from input as well made it work.

I needed ID in output so as to make clear for which ID am I making the prediction

**Comment by w4nderlust** [comment] 2019-03-11 20:14
You don't need that, the predictions are aligned. If you have 10 rows in your test set Ludwig will produce 10 rows as outputs and those will be aligned.
Closing the issue as it is sold, I should probably specify in the docs that you cannot use the came column as both input and output at the moment.

**Closed by w4nderlust** 2019-03-11 20:14 UTC
Labels: question
