### ISSUE TITLE
predict with only_predictions ignores multiple outputs / multiple tasks

### ISSUE THREAD

**Issue by lucaventurini** [uber/ludwig#239] opened 2019-03-21 16:06 UTC
I trained a model with ludwig train, and I now want the predictions for a test dataset which, of course, does not have the label columns.

I'm doing multitask learning and I have two labels, one categorical and one numerical. In reality they are the same column, but since I could not specify the same column twice in the outputs (it gave KeyError) I manually duplicated the column with a different name.

Now when I use ludwig predict --only-predictions it gives a KeyError on the second column. As a workaround I created a fictitious column also in the test dataset, and now it works, but I think there is at least one issue here.

**Comment by w4nderlust** [comment] 2019-03-21 20:23
Thanks for the report. Could you please provide a self contained reproducible example? Either a piece of code that uses the API or a zip containing the yaml and a sample of the CSV)? That would make debugging your issue much easier.

On a side not, I'm curious why would you want to have the same column as both a numerical and a categorical output, as I haven't encountered this use case up until now.

**Comment by lucaventurini** [comment] 2019-03-22 11:11
You find the issue here, search for "KeyError": https://www.kaggle.com/luventu/predict-with-only-predictions-error?scriptVersionId=11925647

As for the reason why I'm doing this, it's an experiment, I'm not 100% sure it will work. The label to predict is a ranking from 0 to 5, so it's a category, but I think it may benefit from a regression task so that wrong labels are anyway closer to the true labels.

**Comment by w4nderlust** [comment] 2019-03-22 18:06
I need something that I can reproduce on my machine to be able to debug it, unfortunately the kaggle link doesn't allow me to debug. Please provide csv + yaml + data sample. Anyway, quickly looking at it, I suspect the `\` in `--only_predictions\` may be messing around and make the script ignore the parameter. Consider adding a space after `--only_predictions`.

I see, it could be interesting. I would suggest to use the newly added `clip` parameter for the numerical value. There are also several ranking losses that i don't have at the moment in Ludwig and could be used for the task, if you end up exploring them, consider doing a PR.

**Comment by w4nderlust** [comment] 2019-03-22 20:36
I actually replicated the issue myself with some synthetic data. The problem was related to the stratify field, not to the fact that there are multiple outputs. Pushed a fix that solved it. I'm closing the issue, but feel free to comment if it doesn't solve it for you.

**Closed by w4nderlust** 2019-03-22 20:36 UTC
Labels: question
