### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.api._v2.keras.initializers' has no attribute 'random_normal'

### ISSUE THREAD

**Issue by Barath19** [uber/ludwig#186] opened 2019-03-08 11:45 UTC

**Comment by w4nderlust** [comment] 2019-03-08 18:10
How do you pretend I will be able to solve this without even a single word to describe it? Please provide a reproducible example, with code, model definition and data.

**Comment by rajputakhil** [comment] 2019-03-09 21:49
Maybe the issue was due to tensorflow 1.13. With that now fixed by @w4nderlust, this error must have gotten resolved. Did @Barath19 try again?

**Comment by Barath19** [comment] 2019-03-10 05:08
I had upgraded to tensorflow 1.13. Got it fixed

**Comment by rajputakhil** [comment] 2019-03-10 06:59
@Barath19 so did converting from 1.13 to 1.12 fixed it? Thanks

**Comment by w4nderlust** [comment] 2019-03-11 19:36
Closing this as it is solved.

**Closed by w4nderlust** 2019-03-11 19:36 UTC
Labels: question

**Comment by amgsharma** [comment] 2019-12-01 21:14
Same error on tensorflow 2.0.0 
Here's the traceback: https://pastebin.com/LRP9gW71
