### ISSUE TITLE
Ludwig does not use tensorflow-gpu?

### ISSUE THREAD

**Issue by athlonshi** [uber/ludwig#73] opened 2019-02-13 18:23 UTC
I have tensorflow-gpu installed and Keras can use the GPU effectively. I only have one GPU.
With ludwig, I tried a regression problem and found the training is very slow. 
`train_stats = ludwig_model.train(data_df=df, logging_level=logging.ERROR, gpus=[0])` 
By watch -n 1 nvidia-smi, I found the training did not actually utilize the GPU but stored the data in the GPU memory anyway. 

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.93       Driver Version: 410.93       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P6000        Off  | 00000000:03:00.0  On |                  Off |
| 26%   44C    P8    19W / 250W |  24289MiB / 24449MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       822      G   /usr/bin/gnome-shell                         186MiB |
|    0      4687      C   /home/yshi1/anaconda3/bin/python           22929MiB |
|    0     10166      C   /home/yshi1/anaconda3/bin/python             977MiB |
|    0     23459      G   /usr/bin/X                                   191MiB |
+-----------------------------------------------------------------------------+

**Comment by us** [comment] 2019-02-13 19:24
Please try this commands:

```
pip uninstall tensorflow
pip install tensorflow-gpu
```

**Comment by athlonshi** [comment] 2019-02-13 19:39
> Please try this commands:
> 
> ```
> pip uninstall tensorflow
> pip install tensorflow-gpu
> ```

This did not solve the problem. The GPU was still not fired up except the memory occupation.

**Comment by w4nderlust** [comment] 2019-02-13 20:11
The fact the the GPU memory is fully utilized by TesnorFlow means that the model is running on GPU.
Try to run the same model from the command line instead of using the API and you should see the TensorFlow messaged printed on stderr.
The fact that the utilization of the GPU is low may have to do with a couple things: your model is really small so there's not much computation per batch to be done, or your batch is really small and so again there's not much computation to be done per batch. To test for this, try to increase the batch size considerably.
Finally, the process that reads data and provides it to TensorFlow at the moment is not super optimized, we are working on improving it, but you may be hitting an i/o bottleneck if your computation per batch is too small.

**Comment by athlonshi** [comment] 2019-02-13 20:36
Thanks, I had a similar thought about it. I had the same setup with keras/tensorflow and its runs much faster and with higher GPU utilization rate. I am thinking the overhead communication cost is quite high between ludwig and tensorflow.  



> The fact the the GPU memory is fully utilized by TesnorFlow means that the model is running on GPU.
> Try to run the same model from the command line instead of using the API and you should see the TensorFlow messaged printed on stderr.
> The fact that the utilization of the GPU is low may have to do with a couple things: your model is really small so there's not much computation per batch to be done, or your batch is really small and so again there's not much computation to be done per batch. To test for this, try to increase the batch size considerably.
> Finally, the process that reads data and provides it to TensorFlow at the moment is not super optimized, we are working on improving it, but you may be hitting an i/o bottleneck if your computation per batch is too small.

**Comment by w4nderlust** [comment] 2019-02-13 22:54
You you can confirm it's running on GPU right? If you run through the command line you get the tf GPU prints and the speed is the same as running it through the API, right?
Yes the communication overhead is one thing we really need to optimize. I'd be curious to take a look at the spcifics of this and run some comparisons, would you be willing to share your tf/keras scripts and your Ludwig model definition or something that replicates it?

**Comment by athlonshi** [comment] 2019-02-13 23:57
I did not have luck with the yaml file input so I did not run through command line. I’d like to see an example yaml file model definition so I can try. 
But I tried to change the batch sizes with 32, 64, 128, 256, and 512. The performances were very different, which indicates the GPU was actually working. For my problem, it appeared that the batch size of 64 gave me the best efficiency, which was several times faster than using 32. 
With batch size of 64, the performance got closer to keras/tensorflow, but it was still slower. 
I have a simple regression problem. With the same network structure and optimizer setup, I had very different results from using Ludwig and keras. I found Ludwig was very sensitive to the initializer parameters. 
My data has proprietary information, so I will need to consolidate my scripts and trim the proprietary information before I can share it. But I will work on it in a day or two. Thanks and congratulations on the great tool!

**Comment by w4nderlust** [comment] 2019-02-14 00:17
As for the YAML examples, you find a bunch [here](https://uber.github.io/ludwig/examples/). Be mindful of the `-` and the indentation.
Glad you were able to make it work decently fast with a bigger batch size.
Regarding the initialization, you can specify which initializer to use, so playing around with that may give you some better results.
Regarding the reproducible example, you can use the `data_synthesyzer` script in `ludwig/data` co create a dataset that looks like yours pretty easily, we use it for integration tests. That should resolve the data issue.
I'm closing the issue, but feel free to either open another one or reach out in private if you can provide me with the comparison script.
You're welcome.

**Closed** 2019-02-14 00:17 UTC
Labels: enhancement
