### ISSUE TITLE
KeyError: 'text_char'  on preprocessing.py

### ISSUE THREAD

**Issue by HichemMaiza** [uber/ludwig#97] opened 2019-02-15 16:54 UTC
### Error Description

The error is raised when you run the `ludwig experiment --data_csv src/data/input/training.csv`  for the second time with the **same file name .csv input file**. you have to change the file name every time you run the experiment. When it creates the .json and the .hdf5 for the first time it works, but when it loads the pre created .json and the .hdf5 files it raise the following error

### Code 
``ludwig experiment --data_csv src/data/input/training.csv --model_definition_file model_definition.yaml``
### Error

> Found hdf5 and json with the same filename of the csv, using them instead
Using full hdf5 and json
Loading data from: src/data/input/training.hdf5
Loading metadata from: src/data/input/training.json
usr/lib/python3.5/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)
Traceback (most recent call last):
  File "/usr/local/bin/ludwig", line 11, in <module>
    load_entry_point('ludwig==0.1.0', 'console_scripts', 'ludwig')()
  File "usr/lib/python3.5/site-packages/ludwig/cli.py", line 86, in main
    CLI()
  File "usr/lib/python3.5/site-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "usr/lib/python3.5/site-packages/ludwig/cli.py", line 67, in experiment
    experiment.cli(sys.argv[2:])
  File "usr/lib/python3.5/site-packages/ludwig/experiment.py", line 548, in cli
    experiment(**vars(args))
  File "usr/lib/python3.5/site-packages/ludwig/experiment.py", line 234, in experiment
    random_seed=random_seed
  File "usr/lib/python3.5/site-packages/ludwig/data/preprocessing.py", line 562, in preprocess_for_training
    [training_set, validation_set, test_set]
  File "usr/lib/python3.5/site-packages/ludwig/data/preprocessing.py", line 777, in replace_text_feature_level
    level)
KeyError: 'text_char'

**Comment by w4nderlust** [comment] 2019-02-15 19:15
I have already solved this issue most likely. Please try to use the current version on the master branch instead of the pip package and let me know if you still have the problem. (a v0.1.1 is coming up with this fix included).

**Comment by ashoksrinivas** [comment] 2019-02-16 03:05
I got into same trouble when I ran the following command 
```
ludwig predict --data_csv path/to/sample_dataset.csv --model path/to/results/experiment_run_0/model/
```
later I saw @w4nderlust  comment "**use the current version on the master branch**" , I did it but still same error **KeyError: 'text_char'**

**Comment by w4nderlust** [comment] 2019-02-17 01:03
Please update to the current master, delete the hdf5 and json files, retrain the model and try again to predict and let me know if the problem is still there.

**Comment by ashoksrinivas** [comment] 2019-02-18 04:01
I updated the Ludwig to current master and as you said removed hdf5 and json files...when I predicted it ...worked like a charm ...got results stored in **result_0**

**Comment by w4nderlust** [comment] 2019-02-18 04:22
Glad it worked! @HichemMaiza I'm closing the issuse, feel free to reopen in case following those instructions doesn't solve it for you.

**Closed by w4nderlust** 2019-02-18 04:22 UTC
Labels: question

**Comment by manugarri** [comment] 2019-04-01 10:02
@w4nderlust I am experiencing this same issue, when I run the experiment command when the hfd5 file had already been generated it fails with a KeyError.

If i understood, the way to bypass this issue is by deleting the hdf5 file every single time you train? this adds a lot of overhead since the same dataset needs to be processed every single time.

**Comment by w4nderlust** [comment] 2019-04-01 18:07
@manugarri no you don't need to do it, the hdf5 and yaml file exist EXACTLY to avoid preprocessing the dataset every time and removing that overhead.
You need to delete the hdf5 and json file only if you change the feature type in a yaml file and try to use the same dataset, which you shouldn't because the type of the column didn't change really, and if it did  change (meaning you modified the csv file), well then that's a different dataset and you should call it with a different name.

**Comment by manugarri** [comment] 2019-04-02 06:51
that is weird @w4nderlust , i am not changing the dataset but any time I try to retrain (i stop the experiment after a while for testing) it gives me that error, maybe I should open a new (and properly documented) issue?

**Comment by w4nderlust** [comment] 2019-04-02 07:35
@manugarri yes please, if you could provide a reproducible example (csv + yaml) I will gladly look into it. Also make sure you are using the current code from master and not the pip package.
