### ISSUE TITLE
TypeError: 'Tensor' object is not callable

### ISSUE THREAD

**Issue by NimalDevelopment** [uber/ludwig#527] opened 2019-09-27 22:53 UTC
Hello, 
I have a big Problem I can't train my model due to the issue in the title.
The StackTrace I get is:

`Traceback (most recent call last):
  File "/usr/local/bin/ludwig", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/ludwig/cli.py", line 108, in main
    CLI()
  File "/usr/local/lib/python3.7/dist-packages/ludwig/cli.py", line 64, in __init__
    getattr(self, args.command)()
  File "/usr/local/lib/python3.7/dist-packages/ludwig/cli.py", line 69, in experiment
    experiment.cli(sys.argv[2:])
  File "/usr/local/lib/python3.7/dist-packages/ludwig/experiment.py", line 472, in cli
    experiment(**vars(args))
  File "/usr/local/lib/python3.7/dist-packages/ludwig/experiment.py", line 203, in experiment
    **kwargs
  File "/usr/local/lib/python3.7/dist-packages/ludwig/train.py", line 311, in full_train
    debug=debug
  File "/usr/local/lib/python3.7/dist-packages/ludwig/train.py", line 475, in train
    **model_definition['training']
  File "/usr/local/lib/python3.7/dist-packages/ludwig/models/model.py", line 576, in train
    bucketing_field
TypeError: 'Tensor' object is not callable
`

My model definition is:
`
input_features:
  -
    name: evaluation
    type: sequence
    encoder: cnnrnn
output_features:
  -
    name: elo
    type: numerical
training:
  batch_size: 32
  epochs: 400
  early_stop: 50
  learning_rate: 0.001
`

My Data looks like:
`elo,evaluation
1063,"12, 30, 16, 2, 17, 28, 1, 5, 7, 0, 39, 0"
1034,"18, 13, 13, 1, 8, 20, 35, 0, 20, 11, 8, 9"
1713,"23, 13, 26, 35, 36, 33, 14, 20, 7, 11, 1, 3, 5, 14, 16, 2, 6, 19, 60, 193, 58, 100, 82, 24, 2985, 1, 230, 0, 0, 0, 0, 0, 0, 0"
1812,"1, 2, 53, 3, 66, 5, 14, 8, 56, 29, 7, 30, 14, 15, 10, 14, 4, 34, 1, 22, 15, 26, 133, 6, 59, 0, 257, 553, 0, 0, 0, 0, 0, 0"
1718,"21, 83, 23, 6, 93, 8, 26, 25, 19, 12, 21, 23, 10, 5, 6, 12, 6, 11, 7, 38, 0, 3, 33, 18, 11, 6, 22, 14, 21, 6, 19, 13, 8, 0, 4158, 0, 5, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0"
1743,"4, 17, 22, 25, 36, 7, 63, 5, 4, 11, 26, 12, 0, 17, 3, 2, 10, 16, 3, 19, 17, 13, 2, 5, 49, 40, 7, 1, 42, 10, 2, 36, 48, 8, 1175, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0"
1534,"5, 10, 23, 5, 16, 39, 13, 14, 2, 34, 11, 10, 20, 0, 0, 7, 16, 20, 5, 16, 12, 0"
1500,"2, 10, 18, 3, 14, 26, 7, 15, 5, 12, 3, 25, 21, 0, 14, 12, 5, 14, 49, 24, 0, 0"
2070,"17, 10, 17, 12, 6, 24, 3, 12, 23, 24, 35, 4, 14, 8, 59, 29, 28, 55, 59, 13, 15, 218"`

Can anyone help me. I need to commit this Project by Monday

**Comment by msaisumanth** [comment] 2019-09-28 21:43
input features and output features need to be lists in the yaml. like this:

```yaml
input_features:
     - 
         type:
output_features:
     -
         type:
```

**Comment by NimalDevelopment** [comment] 2019-09-28 23:15
Yeah github made it looking that way. I have it the way you mentioned. Also tried it in python the same error occurs

**Comment by NimalDevelopment** [comment] 2019-09-29 12:03
```yaml
input_features:
  -
    name: evaluation
    type: sequence
    encoder: cnnrnn
output_features:
  -
    name: elo
    type: numerical
```

that's how it currently looks

**Comment by w4nderlust** [comment] 2019-09-30 14:45
Can you please provide a compete reproducible example? Either by providing a sample of the data or by providing synthetic data (use ludwig's data.dataset_synthesizer)? It will make it easier to solve the problem.

**Comment by NimalDevelopment** [comment] 2019-09-30 15:37
https://hub.gke.mybinder.org/user/jupyterlab-jupyterlab-demo-twe0hacd/lab/tree/LudwigTest
Hopefully, that's helping

**Comment by NimalDevelopment** [comment] 2019-09-30 16:15
```python
from ludwig.api import LudwigModel
import ludwig
import pandas as pd


df = pd.read_csv("/home/nimal/Dokumente/Git/filter/src/nn/resources/evaluated.csv")


#dataset = ludwig.api.build_dataset("/home/nimal/Dokumente/Git/filter/src/nn/resources/evaluated.csv", "evaluation", None)
#print(dataset)

df['evaluation'] = [x.replace(',', '\\,')for x in df['evaluation']]
model_definition ={
    'input_features':[
        {'name':'evaluation', 'type':'sequence'}
    ],
    'output_features':[
        {'name':'elo', 'type':'numerical'}
    ]
}
print('creating model')
model = LudwigModel(model_definition)
print('training model', "evaluation")
train_stats = model.train(df)
model.close()
```
The csv data you'll find here : https://pastebin.com/iNnE4wtL

Sorry I don' know hot to use data.dataset_synthesizer

**Comment by w4nderlust** [comment] 2019-10-06 02:33
@NimalDevelopment there are a few problems with your script, let me try to explain.

The first problem is the fact that for sequence nad timeseries features the defaultseparator is whitespace, so your code should be:
```
df['evaluation'] = [x.replace(',', '')for x in df['evaluation']]
```
The second problem is that `evaluation` is a protected keyword that is used internaly in Ludwig. This made me realize I should probably change the way ideal with the name of input and output features in the code in order to remove limitations on the name of the features. But until I fix it, please just don't use the `evaluation` name in your dataframe and model definition. Do something like:
```
df['evalu'] = [x.replace(',', '')for x in df['evaluation']]
```
Finally, I'm not sure what those numbers in evalu mean, but most likely you want to treat them as numbers, while using sequence treats them as identifiers/tokens. You want to use timeseries as type for that.
All in all your corrected script looks like:
```
from ludwig.api import LudwigModel
import pandas as pd
import logging

df = pd.read_csv("issue_527.csv")
df['evalu'] = [x.replace(',', '')for x in df['evaluation']]

model_definition ={
    'input_features':[
        {'name':'evalu', 'type':'timeseries'}
    ],
    'output_features':[
        {'name':'elo', 'type':'numerical'}
    ]
}
print('creating model')
model = LudwigModel(model_definition, logging_level=logging.DEBUG)
print('training model', "evaluation")
train_stats = model.train(df)
model.close()
```
Now, if you run this as is you will not get great results right out of the bat, I suggest you to start by reducing the learning rate by one or two orders of magnitude and then plkay around with the other parameters.

Let me know if this solves your issue anyway

**Comment by w4nderlust** [comment] 2019-10-06 02:33
Marking as enhancement to remind myself to change the way names of the input and output features are treated in `model.py`.

**Closed** 2020-01-21 21:39 UTC
Labels: enhancement, waiting for answer
