### ISSUE TITLE
unable to install ludwig due to gmpy

### ISSUE THREAD

**Issue by Kantshun** [uber/ludwig#488] opened 2019-08-13 06:42 UTC
**Describe the bug**
I can't install ludwig in win10 due to gmpy installation go wrong.

**To Reproduce**
1.download gmpy-master.zip from github and unzip it.
2.in terminal window, input command "python setup.py install"
3.minuters later, see error.
![image](https://user-images.githubusercontent.com/31396222/62920480-77ae2d80-bdd8-11e9-9afe-752cf55716e5.png)

**Environment (please complete the following information):**
 - OS: win10 professional
 - Version: i don't know
- Python version: 3.7.4
- Ludwig version: ludwig-master

**Additional context**

**Comment by MarchingVoxels** [comment] 2019-08-13 07:19
Yep, having the exact same problem here, with python version of 3.7.4 and trying to install with pip

**Comment by carlogrisetti** [comment] 2019-08-13 12:25
Duplicate of #452 
Install from master repo and it will be ok - gmpy prerequisite has been removed.

**Closed** 2019-08-13 21:02 UTC
Labels: duplicate
